language: r
cache: packages
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-7

addons:
  apt:
    packages:
      - libssl-dev
      - libhdf5-dev
      - libhdf5-serial-dev
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
