language: r
cache: packages
addons:
  apt:
    packages:
      - libssl-dev
      - libhdf5-7
      - libhdf5-dev
      - libhdf5-serial-dev
      - libgdal-dev
      - libgdal1-dev
      - libproj-dev
      
